### ISSUE TITLE
Hide File Broken

### ISSUE THREAD

**Issue by FlyingFaller** [TheGreenPig/BetterDiscordPlugins#1]
In a DM with a large PDF the file view button behaves as follows:

Show File: Shows the file view as intended
Hide File: Does not _hide_ the file but it does update the icon 
Show File (again): Shows a duplicate view of the file next to the original (both are functional lol)
Hide File (again): Hides one of the file views but leaves the other

Clicking show or hide more repeats in the same way, opening two file views or closing one. i.e. once you open a file view you can't close it unless you leave the DM.

**Comment by TheGreenPig** [comment]
Should be fixed in `1.0.1`
