### ISSUE TITLE
PermissionsViewer only showing permissions for users with no roles

### ISSUE THREAD

**Issue by NefariousIntent2** [TheGreenPig/BetterDiscordPlugins#15]
hey @TheGreenPig sorry to bother on a completely random repo, but do you know why I can't see permissions for anyone with roles? As soon the user has a role I can't see the permissions at all. If you could fix this, it would be highly appreciated. Thanks.

**Comment by NefariousIntent2** [comment]
Nevermind, I found the issue. BetterRoleColors messed up PermissionsViewer

**Comment by TheGreenPig** [comment]
This is not only the wrong repo, I'm not even the author of PermissionsViewer? The issues section here is intended for people reporting issues and bugs about **my** plugins. Please ask in the plugin-support channel of the bd server or create an issue in the correct repo.
I have created a pull request for PermissionsViewer, that doesn't mean that I am responsible for maintaining it though.

**Comment by NefariousIntent2** [comment]
@TheGreenPig I was meaning your fix of permissions viewer. However I found BetterRoleColors fucked the permissions up
