### ISSUE TITLE
Great project :) storage settings save will be added in the future.And the TOP function?

### ISSUE THREAD

**Issue by Aram-Lin** [TheGreenPig/BetterDiscordPlugins#16]
FileViewer.plugin.js

It works fine, but it switches the preset size every time it's turned on.
If you are chatting with someone else, if you have the top feature, you can chat and view the PDF at the same time.
Will you consider adding it in the future?

**Comment by TheGreenPig** [comment]
In the newest update, the size of the preview gets saved, so if you close and open it again it should have the size as before. It isn't actually cached or anything, though, so if you switch channels/rerender the preview icon that size will reset.

Not sure what you mean by "top feature"? If you mean something like the preview floating on top like a picture in picture mode, I will probably not add it. That's pretty complex, just shift click the icon to open the preview in your browser.
