### ISSUE TITLE
[File Viewer] Equations do not render in .docx

### ISSUE THREAD

**Issue by KalasLavas** [TheGreenPig/BetterDiscordPlugins#3]
As stated in title, equations fail to render for .docx files
![image](https://user-images.githubusercontent.com/64844410/142587819-322077ad-44bc-4052-a976-210f0774c695.png)
This seems to be the issue of the Google's viewer rather than plugins, give a shot to the [Office Web apps viewer](https://gist.github.com/tzmartin/1cf85dc3d975f94cfddc04bc0dd399be)

**Comment by TheGreenPig** [comment]
Thanks for the tip! I added this in the newest `1.0.2` update.
