### ISSUE TITLE
[BetterMessageLinks] Invalid message link crashes discord

### ISSUE THREAD

**Issue by FrostBird347** [TheGreenPig/BetterDiscordPlugins#4]
Opening any channel with a message link that returns a 403 response will crash discord.

**Comment by Drflash55** [comment]
Can confirm that this does indeed happen.
![image](https://user-images.githubusercontent.com/13694448/146565515-2ccd5b57-df1b-4743-ab2b-9e81d53961ca.png)

**Comment by TheGreenPig** [comment]
I already fixed this [here](https://github.com/TheGreenPig/BetterDiscordPlugins/commit/6ebc328bde80551435ae91b8da283136913e845b), but haven't updated the version yet. You can either download from source again or wait for me to bump the version shortly.

**Comment by TheGreenPig** [comment]
I just bumped the version `1.2.6`. Wait for the notification or download from source, like I said.
