### ISSUE TITLE
BetterMessageLinks

### ISSUE THREAD

**Issue by lolpowerluke** [TheGreenPig/BetterDiscordPlugins#5]
if possible, could you make it so we can scroll the popup?
this would make it so we can read long messages without having to go to the message itself
![image](https://user-images.githubusercontent.com/47672899/146640720-8b6a84a5-300f-406c-97cf-028409db8605.png)

**Comment by TheGreenPig** [comment]
Added in `1.4.0`, please wait for the Update prompt or update manually.
