### ISSUE TITLE
BetterMessageLinks incorrect attachment message

### ISSUE THREAD

**Issue by machineonamission** [TheGreenPig/BetterDiscordPlugins#6]
![image](https://user-images.githubusercontent.com/35177464/146664268-9a2261ed-ddb1-40ef-a298-39fe4bd7e1ca.png)

https://cdn.discordapp.com/attachments/829976400056156160/919091349385535578/wUyezf0WmWdPRbeY.mp4

**Comment by TheGreenPig** [comment]
Should be fixed now, please wait for the Update promt or update manually.
