### ISSUE TITLE
[BetterMessageLinks] Embedded Links are also replaced

### ISSUE THREAD

**Issue by rakosi2** [TheGreenPig/BetterDiscordPlugins#8]
Could Embedded links keep the displayed text instead of changing it to `<Message>` Currently this is what I see:
![image](https://user-images.githubusercontent.com/6037087/147778945-1e9c97dd-d62f-4b8c-93f3-a4c42cbe374b.png)
what it should be shown:
![image](https://user-images.githubusercontent.com/6037087/147779099-d7a3e961-272f-46b3-be39-6e3830caf443.png)
I am using version v1.4.2

ps could you also update the plugins GitHub link as it is broken
https://github.com/TheGreenPig/BetterDiscordPlugins/main/BetterMessageLinks/BetterMessageLinks.plugin.js

**Comment by TheGreenPig** [comment]
Thanks for the info, yes I will add this in the next update.
