### ISSUE TITLE
[BetterMessageLinks] Can't open embed links

### ISSUE THREAD

**Issue by rakosi2** [TheGreenPig/BetterDiscordPlugins#9]
Referring to `[text](https://link-url-here.org/example)`  where clicking on it would open `https://link-url-here.org/text`

If there is just a link plainly in an embed, it opens just fine.

**Comment by TheGreenPig** [comment]
BetterMessageLinks shouldn't touch any links that aren't discord attachment or message links. Please make sure you are on the newest version, it shouldn't be an issue there.

**Comment by rakosi2** [comment]
Version 1.4.9 fixed it
